env: standard
runtime: nodejs16
service: default
instance_class: F1
handlers:
  - url: /.*
    secure: always
    script: auto
automatic_scaling:
  target_throughput_utilization: 0.7
  min_instances: 0
  max_instances: 30
  max_concurrent_requests: 36
